import type { IBooking } from "@/models/booking";
import type { IDriver } from "@/models/driver";
import type { IPartner } from "@/models/partner";
import type { useTranslations } from "next-intl";
import type { Dispatch, SetStateAction } from "react";

export type AdminRideCardDialogsProps = {
  t: ReturnType<typeof useTranslations>;
  booking: IBooking;
  bookingId: string;
  currencySymbol: string;
  totalAmountValue: number;
  partnerMargin: number;
  setPartnerMargin: Dispatch<SetStateAction<number>>;
  marginPreviewAmount: number;
  partnerPayoutPreview: number;
  approvalButtonLabel: string;
  isApprovingThisBooking: boolean;
  isPartnerReviewPending: boolean;
  showPartnerApprovalModal: boolean;
  setShowPartnerApprovalModal: Dispatch<SetStateAction<boolean>>;
  showAssignDriverModal: boolean;
  setShowAssignDriverModal: Dispatch<SetStateAction<boolean>>;
  showAssignPartnerModal: boolean;
  setShowAssignPartnerModal: Dispatch<SetStateAction<boolean>>;
  selectedDriver: string;
  setSelectedDriver: Dispatch<SetStateAction<string>>;
  selectedPartner: string;
  setSelectedPartner: Dispatch<SetStateAction<string>>;
  assignPartnerMargin: number;
  setAssignPartnerMargin: Dispatch<SetStateAction<number>>;
  drivers: IDriver[];
  partners: IPartner[];
  assigningId: string | null;
  approvingPartnerId: string | null;
  handleApprovePartnerReview: (bookingId: string, margin: number) => Promise<boolean>;
  handleAssignDriver: (bookingId: string, driverId: string) => Promise<void>;
  handleAssignPartner: (bookingId: string, partnerId: string) => Promise<void>;
};
