import type { IFormStyle } from "@/models/form-layout";

// ─── Default Style Fallback ────────────────────────────────────────────────
export const CUSTOM_EMBEDDABLE_DEFAULT_STYLE: IFormStyle = {
  backgroundColor: "#ffffff",
  backgroundOpacity: 90,
  glassEffect: true,
  borderRadius: "0.75rem",
  borderColor: "#e2e8f0",
  borderWidth: "0px",
  primaryColor: "#0f172a",
  headingColor: "#1e293b",
  labelColor: "#475569",
  textColor: "#64748b",
  showHeader: true,
  headingText: "Trip Booking",
  subHeadingText: "Book your ride in seconds",
  headingAlignment: "center",
  showFooter: true,
  footerText: "By submitting my data I agree to be contacted",
  showSteps: true,
  showFooterImages: true,
  inputBackgroundColor: "#ffffff",
  inputBorderColor: "#e2e8f0",
  inputTextColor: "#1e293b",
  bookingTypeButtonColor: "#0f172a",
  bookingTypeButtonTextColor: "#ffffff",
  buttonText: "",
  buttonColor: "",
  buttonTextColor: "",
  buttonWidth: "full",
  buttonAlignment: "center",
  showLabels: false,
  inputSize: "default",
  fieldGap: 12,
  inputBorderRadius: "0.5rem",
  buttonPosition: undefined,
};
